const pages={home:'pages/home.html',breathe:'pages/breathe.html',journal:'pages/journal.html',future:'pages/future.html',comfort:'pages/comfort.html',poetry:'pages/poetry.html',about:'pages/about.html'};
const templates={
  comfort: `<section class="center-page page-enter"><span class="eyebrow">04 · borrow warmth</span><h1>For when your mind is <span>too loud.</span></h1><p class="lead">Take one sentence. Keep it for as long as you need. Then ask for another.</p><div class="comfort-card glass"><p id="comfortLine">You are allowed to miss someone and still choose yourself.</p><button class="btn primary" id="comfortNext">Another little reminder</button></div><p class="tiny smalllead">You don't have to turn pain into a lesson tonight. Sometimes it can just be pain, and you can still be cared for while it passes.</p></section>
<section class="principles glass"><div><b>Soft does not mean weak.</b><p>Rest, tears, quiet and asking for company can all be forms of taking care of yourself.</p></div><div><b>You can have mixed feelings.</b><p>Missing the good parts doesn't mean you need the whole relationship back.</p></div><div><b>Tomorrow is allowed to be different.</b><p>A feeling can be real without being permanent. Let it move through you at its own pace.</p></div></section>
`,
  about: `<section class="center-page page-enter"><span class="eyebrow">06 · about bloom</span><h1>A small place to <span>land.</span></h1><p class="lead">Bloom was made around a simple idea: when someone is having a difficult day, the internet can contain one small corner that asks nothing from them.</p><div class="principles glass"><div><b>Nothing to perform.</b><p>You can visit for thirty seconds or an hour. There is no streak you can fail and no mood you have to reach.</p></div><div><b>Make the atmosphere yours.</b><p>Soft Light, Night Blue and Morning Mist are remembered on this device so you can choose what feels right.</p></div><div><b>Private by default.</b><p>The journal is stored locally in your browser in this version. It is not uploaded to a server.</p></div><div><b>For real support too.</b><p>If sadness becomes overwhelming or you feel unsafe, a trusted person or qualified mental-health professional can offer something a website cannot: real human support.</p></div></div></section>
`,
  breathe: `<section class="center-page page-enter"><span class="eyebrow">01 · slow down</span><h1>Let's make <span>one minute</span> quieter.</h1><p class="lead">Nothing to fix. Nothing to prove. Follow the circle and let your shoulders drop a little.</p><div class="breath-wrap"><div class="breath-orb" id="breathOrb"><span id="breathText">Ready</span></div></div><div class="timer" id="breathTimer">60</div><button class="btn primary" id="startBreath">Start 60 seconds</button><p class="tiny">If counting feels annoying, ignore it. Your breathing does not have to be perfect.</p></section>
<section class="three-notes"><div><b>In</b><p>Let the breath arrive without forcing it.</p></div><div><b>Hold softly</b><p>Notice your feet, your hands, the room around you.</p></div><div><b>Out</b><p>Imagine making a little more room inside yourself.</p></div></section>
`,
  poetry: `<section class="page-head page-enter"><span class="eyebrow">05 · read slowly</span><h1>A few words for the <span>quiet hours.</span></h1><p class="lead">Original little poems for moments when advice feels like too much.</p></section><article class="poem-card glass"><span class="poem-mark">❋</span><h2 id="poemTitle">After the Rain</h2><div class="poem-text" id="poemText"></div><div class="poem-actions"><button class="btn primary" id="nextPoem">Another poem →</button><button class="btn ghost" id="copyPoem">Copy</button></div></article><div class="poetry-note glass"><b>You can read the same poem twice.</b><p>Some words change when you return to them. That is allowed too.</p></div>
`,
  future: `<section class="center-page page-enter"><span class="eyebrow">03 · look forward</span><h1>There is still <span>so much life.</span></h1><p class="lead">Not a giant plan. Just little doors you might like to open someday.</p><div class="future-card glass"><div class="sun">☼</div><h2 id="futurePrompt">What would you love to experience for the first time?</h2><button class="btn ghost" id="shuffleFuture">Give me another idea ↻</button><div class="chips" id="futureChips"></div></div></section><section class="mini-grid"><div><b>For a free afternoon</b><p>Walk somewhere you have never walked. Take photos of ordinary things. Buy a snack you have never tried.</p></div><div><b>For a difficult evening</b><p>Shower. Change the sheets. Put on something familiar. Make tea. Let the evening be small.</p></div><div><b>For a future morning</b><p>Wake up early once. See the sky change. You don't need a reason beyond being there.</p></div></section>
`,
  journal: `<section class="page-head page-enter"><span class="eyebrow">02 · let it out</span><h1>A page that <span>doesn't interrupt.</span></h1><p class="lead">Write badly. Write honestly. Write three words and leave. Your journal stays in this browser on this device.</p></section><section class="journal-grid"><div class="prompt glass"><span>today's gentle prompt</span><h2 id="promptText">What would feel kind to you right now?</h2><button class="text-btn" id="newPrompt">Another prompt ↻</button><div class="prompt-foot">No one is grading this.</div></div><div class="editor glass"><textarea id="journalText" placeholder="Start anywhere…\\n\\nYou could begin with: “Today I…”"></textarea><div class="editor-foot"><span id="wordCount">0 words</span><span id="saveState">Not saved yet</span><div><button class="btn ghost small" id="clearJournal">Clear</button><button class="btn primary small" id="saveJournal">Save</button></div></div></div></section>
`,
  home: `<section class="hero page-enter"><div class="eyebrow">a quiet corner of the internet · day <span id="visitCount">1 gentle visit</span></div><h1>You don't have to forget.<br><span>You can begin again.</span></h1><p class="lead">A little place to breathe when thoughts get loud. Come here for one minute, ten minutes, or simply because you want somewhere soft to land.</p><div class="actions"><a class="btn primary" href="#/breathe">Take a breath <span>→</span></a><a class="btn ghost" href="#/poetry">Read something gentle</a></div><div class="daily-card glass"><div class="daily-icon">✦</div><div><span class="label">a little note for today</span><h3 id="dailyTitle">A tiny beginning</h3><p id="dailyText">You do not need to feel completely okay today. One gentle thing is enough.</p><button class="text-btn" id="dailyAction">Open a window →</button></div></div></section>
<section class="section-head"><div><span class="eyebrow">choose what you need</span><h2>There is no right way to use Bloom.</h2></div><p>Stay for a moment. Wander around. Leave and come back tomorrow. Nothing here is a test.</p></section>
<section class="feature-grid"><a href="#/breathe" class="feature micro-card"><b>01 · SLOW DOWN</b><div class="feature-icon">◌</div><h3>Breathe</h3><p>A tiny guided pause for when your chest feels full and your thoughts won't sit still.</p><span>60 seconds · gentle</span></a><a href="#/journal" class="feature micro-card"><b>02 · LET IT OUT</b><div class="feature-icon">✎</div><h3>Write</h3><p>Put the messy version on a page. No audience. No perfect sentences. Just somewhere for it to go.</p><span>private · on this device</span></a><a href="#/future" class="feature micro-card"><b>03 · LOOK AHEAD</b><div class="feature-icon">✦</div><h3>Future</h3><p>Small ideas for tomorrow, next month, and the life that is still waiting to surprise you.</p><span>shuffle · explore</span></a><a href="#/comfort" class="feature micro-card"><b>04 · BORROW WARMTH</b><div class="feature-icon">♡</div><h3>Comfort</h3><p>Short reminders for the moments when your own mind is being harder on you than it should.</p><span>tap for another</span></a><a href="#/poetry" class="feature micro-card"><b>05 · READ SLOWLY</b><div class="feature-icon">❋</div><h3>Poetry</h3><p>Original little pieces to read when you don't want advice. Sometimes words can simply sit beside you.</p><span>new poem · daily</span></a><a href="#/about" class="feature micro-card"><b>06 · MAKE IT YOURS</b><div class="feature-icon">☼</div><h3>Your space</h3><p>Choose the atmosphere, turn on an ambient tone, and make this corner feel like yours.</p><span>soft · night · mist</span></a></section>
<section class="night-note"><div id="constellation" class="constellation"></div><span class="eyebrow">a thought to keep</span><p>“You are not behind. You are becoming, even on the days when it doesn't look like anything is happening.”</p><span class="tiny">Come back whenever you need a softer five minutes.</span></section>
`
};
const moods={soft:{name:'Soft Light',icon:'☼',desc:'Warm, golden and gentle'},night:{name:'Night Blue',icon:'☾',desc:'Quiet, deep and dreamy'},mist:{name:'Morning Mist',icon:'☁',desc:'Fresh, airy and hopeful'}};
const daily=[
 ['A tiny beginning','You do not need to feel completely okay today. One gentle thing is enough.','Open a window'],
 ['A softer thought','Some chapters end without taking your whole story with them. There is still so much unwritten.','Write three lines'],
 ['For tonight','If your mind keeps returning to yesterday, give it somewhere kinder to go: music, a page, the sky.','Look at the sky'],
 ['A little courage','Healing can be wonderfully ordinary. Tea. A walk. Clean sheets. A laugh you did not expect.','Do one small thing'],
 ['You are still becoming','The person you are becoming deserves the same patience you give everyone else.','Be kind to yourself'],
 ['No rush','There is no deadline for feeling better. Let today be today. Tomorrow can wait.','Take five slow breaths'],
 ['Something ahead','There are mornings you have not lived yet that will feel lighter than you imagine.','Imagine one']
];
const poems=[
 ['After the Rain','Some mornings arrive quietly,\nnot asking you to be happy,\nonly asking you to open the curtain\nand notice the light has returned.\n\nYou can carry yesterday gently\nwithout carrying it everywhere.\nLet the day be small.\nLet your heart take its time.'],
 ['A Place for Tomorrow','There is a version of tomorrow\nthat has never heard the old story.\nShe is still learning your favorite songs,\nstill waiting for your laughter,\nstill becoming home.\n\nYou do not have to chase her.\nJust keep walking softly.'],
 ['Little Things','A cup of tea.\nA window left open.\nA song you forgot you loved.\nThe sky turning gold on an ordinary road.\n\nSometimes healing enters\nwithout announcing its name.'],
 ['When It Gets Quiet','If the room becomes too quiet,\nput one gentle thing inside it:\na page, a melody, a plant, a warm light.\n\nYou are not required\nto solve your whole life tonight.\nOnly make tonight kinder.'],
 ['The Life Still Waiting','There are places you have not wandered,\nsmall cafés you have not found,\npeople whose names you do not know yet,\nand songs that have not become yours.\n\nYour story is larger\nthan the page that hurt.']
];
const prompts=['What would feel kind to you right now?','What is something you are proud you survived?','What would you tell your younger self tonight?','What tiny thing made today a little nicer?','What do you want your next chapter to feel like?','If tomorrow were gentle, what would it contain?','What are you ready to stop carrying alone?'];
const futurePrompts=['What would you love to experience for the first time?','Where would you go for a peaceful morning?','What hobby would you try just for fun?','What would make next month 1% brighter?','What kind of person do you want to become for yourself?','What small plan could give you something to look forward to?'];
const comfort=['You are allowed to miss someone and still choose yourself.','A hard night is not a prediction of your whole life.','You do not need to be over it today. Be gentle with today.','The future does not need permission from the past.','Rest is still progress when your heart is tired.','You deserve friendships, laughter and ordinary beautiful days.','There is no prize for healing quickly.','You can love what was and still make room for what is next.'];
const app=document.getElementById('app');
const get=(k,d='')=>localStorage.getItem(k)??d; const set=(k,v)=>localStorage.setItem(k,v);
function dayIndex(arr){const d=new Date();return (d.getFullYear()*372+d.getMonth()*31+d.getDate())%arr.length}
function currentMood(){return get('bloomMood','soft')}
function applyMood(k=currentMood()){if(!moods[k])k='soft';document.body.dataset.mood=k;set('bloomMood',k);document.documentElement.style.setProperty('--mood',k);}
function shell(content,key){
 const links=[['home','Home'],['breathe','Breathe'],['journal','Journal'],['future','Future'],['comfort','Comfort'],['poetry','Poetry']];
 const navlinks=links.map(x=>'<a href="#/'+x[0]+'">'+x[1]+'</a>').join('');
 const mobile=links.map(x=>'<a href="#/'+x[0]+'">'+x[1]+'</a>').join('');
 const bottom=[['home','⌂','Home'],['breathe','◌','Breathe'],['journal','✎','Write'],['future','✦','Future'],['comfort','♡','Comfort']].map(x=>'<a href="#/'+x[0]+'" class="'+(key===x[0]?'active':'')+'"><span>'+x[1]+'</span>'+x[2]+'</a>').join('');
 const moodOptions=Object.entries(moods).map(([id,m])=>'<button class="mood-option" data-mood="'+id+'"><span class="mood-icon">'+m.icon+'</span><span><b>'+m.name+'</b><small>'+m.desc+'</small></span><i>✓</i></button>').join('');
 return '<div class="ambient-layer"><div class="aurora a1"></div><div class="aurora a2"></div><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><div class="stars"></div><div class="grain"></div></div><main class="site"><nav class="nav"><div class="nav-left"><a class="back" href="#" id="backBtn">← <span>Back</span></a><a class="logo" href="#/home">bloom<span>°</span></a></div><div class="navlinks">'+navlinks+'</div><div class="nav-tools"><button class="mood-button" id="moodBtn">☼ <span>Soft Light</span></button><button class="sound" id="soundBtn">♪</button><button class="menu" id="menuBtn">☰</button></div></nav><div class="mobile-menu" id="mobileMenu">'+mobile+'</div><div class="mood-panel" id="moodPanel"><div class="mood-panel-head"><div><b>Choose your atmosphere</b><small>Your choice stays on this device.</small></div><button id="closeMood">×</button></div><div class="mood-options">'+moodOptions+'</div></div>'+content+'<footer class="footer"><span>For the days that feel too quiet.</span><div><a href="#/about">About Bloom</a><a href="#/poetry">A few words</a></div></footer><div class="bottom-nav">'+bottom+'</div></main>';
}
function route(){let key=location.hash.replace('#/','')||'home';if(!templates[key])key='home';const html=templates[key];app.innerHTML=shell(html,key);applyMood();updateMoodUI();bind(key);document.querySelectorAll('.navlinks a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#/${key}`));window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>document.querySelectorAll('.page-enter').forEach(x=>x.classList.add('show')))}
function updateMoodUI(){const k=currentMood(),m=moods[k];const b=document.getElementById('moodBtn');if(b)b.innerHTML=`${m.icon} <span>${m.name}</span>`;document.querySelectorAll('.mood-option').forEach(x=>x.classList.toggle('selected',x.dataset.mood===k))}
function bind(key){
 const back=document.getElementById('backBtn');back.onclick=e=>{e.preventDefault();if(document.referrer&&history.length>1)history.back();else location.hash='#/home'};
 const panel=document.getElementById('moodPanel');document.getElementById('moodBtn').onclick=()=>panel.classList.toggle('open');document.getElementById('closeMood').onclick=()=>panel.classList.remove('open');document.querySelectorAll('.mood-option').forEach(b=>b.onclick=()=>{applyMood(b.dataset.mood);updateMoodUI();panel.classList.remove('open');spark();toast(`${moods[b.dataset.mood].name} selected`)});
 const menu=document.getElementById('mobileMenu');document.getElementById('menuBtn').onclick=()=>menu.classList.toggle('open');menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));
 document.addEventListener('click',e=>{if(panel.classList.contains('open')&&!panel.contains(e.target)&&!e.target.closest('#moodBtn'))panel.classList.remove('open')},{once:true});
 document.getElementById('soundBtn').onclick=toggleAudio;
 if(key==='home')home(); if(key==='breathe')breathe(); if(key==='journal')journal(); if(key==='future')future(); if(key==='comfort')comfortPage(); if(key==='poetry')poetry();
}
function home(){const d=daily[dayIndex(daily)];let t=document.getElementById('dailyTitle');if(t){document.getElementById('dailyTitle').textContent=d[0];document.getElementById('dailyText').textContent=d[1];document.getElementById('dailyAction').textContent=d[2];document.getElementById('dailyAction').onclick=()=>toast('Saved as a tiny plan for today ✦');}
 document.querySelectorAll('.micro-card').forEach(c=>c.onclick=()=>{c.classList.toggle('done');spark()}); const streak=Number(get('bloomVisitStreak','0'))+1;set('bloomVisitStreak',String(streak));const el=document.getElementById('visitCount');if(el)el.textContent=`${Math.min(streak,99)} gentle visit${Math.min(streak,99)===1?'':'s'}`;const canvas=document.getElementById('constellation');if(canvas){for(let i=0;i<18;i++){const s=document.createElement('i');s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*3+'s';canvas.appendChild(s)}}}
function breathe(){let orb=document.getElementById('breathOrb'),txt=document.getElementById('breathText'),timer=document.getElementById('breathTimer'),btn=document.getElementById('startBreath');if(!btn)return;btn.onclick=()=>{let t=60;btn.disabled=true;orb.classList.add('running');txt.textContent='In…';timer.textContent='60';let iv=setInterval(()=>{t--;timer.textContent=t;txt.textContent=(t%8<4)?'In…':'Out…';if(t<=0){clearInterval(iv);orb.classList.remove('running');txt.textContent='You made it';btn.disabled=false;spark();toast('A minute just became softer.')}} ,1000)};}
function journal(){let i=Number(get('bloomPromptIndex','0'))%prompts.length,p=document.getElementById('promptText');p.textContent=prompts[i];document.getElementById('newPrompt').onclick=()=>{i=(i+1)%prompts.length;set('bloomPromptIndex',i);p.textContent=prompts[i];spark()};let ta=document.getElementById('journalText'),state=document.getElementById('saveState');ta.value=get('bloomJournal','');document.getElementById('saveJournal').onclick=()=>{set('bloomJournal',ta.value);state.textContent='Saved privately on this device · '+new Date().toLocaleTimeString();toast('Your words are safe here ✦')};document.getElementById('clearJournal').onclick=()=>{ta.value='';localStorage.removeItem('bloomJournal');state.textContent='Cleared'};const count=document.getElementById('wordCount');ta.oninput=()=>count.textContent=`${ta.value.trim()?ta.value.trim().split(/\s+/).length:0} words`}
function future(){let i=dayIndex(futurePrompts),p=document.getElementById('futurePrompt');p.textContent=futurePrompts[i];document.getElementById('shuffleFuture').onclick=()=>{i=(i+1)%futurePrompts.length;p.textContent=futurePrompts[i];spark()};const chips=['learn something','watch a sunrise','make art','visit somewhere new','cook something','read a book','take a long walk','dance','take photos','plant something','try a new café','make a playlist'];document.getElementById('futureChips').innerHTML=chips.map(x=>`<button class="chip" onclick="this.classList.toggle('picked');this.textContent=this.classList.contains('picked')?'✓ '+this.textContent:this.textContent">${x}</button>`).join('')}
function comfortPage(){let i=dayIndex(comfort),line=document.getElementById('comfortLine');line.textContent=comfort[i];document.getElementById('comfortNext').onclick=()=>{i=(i+1)%comfort.length;line.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:450});line.textContent=comfort[i];spark()}}
function poetry(){let i=dayIndex(poems),title=document.getElementById('poemTitle'),text=document.getElementById('poemText');title.textContent=poems[i][0];text.textContent=poems[i][1];document.getElementById('nextPoem').onclick=()=>{i=(i+1)%poems.length;title.textContent=poems[i][0];text.textContent=poems[i][1];spark()};document.getElementById('copyPoem').onclick=async()=>{try{await navigator.clipboard.writeText(title.textContent+'\n\n'+text.textContent);toast('Poem copied');}catch(e){toast('Copy is not available here')}}}
let audio=null;function toggleAudio(){const b=document.getElementById('soundBtn');if(audio){audio.osc.stop();audio.ctx.close();audio=null;b.textContent='♪';toast('Ambient off');return}const AC=window.AudioContext||window.webkitAudioContext;if(!AC){toast('Ambient audio is not supported');return}const ctx=new AC(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=currentMood()==='night'?174:currentMood()==='mist'?220:196;gain.gain.value=.009;osc.connect(gain).connect(ctx.destination);osc.start();audio={ctx,osc};b.textContent='◼';toast('Soft ambient tone on')}
function spark(){for(let i=0;i<12;i++){const s=document.createElement('i');s.textContent=Math.random()>.45?'✦':'·';s.style.position='fixed';s.style.left=(45+Math.random()*10)+'%';s.style.top=(45+Math.random()*10)+'%';s.style.color='var(--accent)';s.style.pointerEvents='none';s.style.zIndex=100;s.animate([{transform:'scale(0)',opacity:0},{transform:`translate(${(Math.random()-.5)*260}px,${(Math.random()-.5)*190}px) scale(1)`,opacity:1},{opacity:0}],{duration:1100}).onfinish=()=>s.remove()}}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
window.addEventListener('hashchange',route);route();
