const pages={home:'pages/home.html',breathe:'pages/breathe.html',journal:'pages/journal.html',future:'pages/future.html',comfort:'pages/comfort.html',poetry:'pages/poetry.html',about:'pages/about.html'};
const moods={
  soft:{name:'Soft Light',icon:'☼',class:'mood-soft',desc:'Warm, gentle daylight'},
  night:{name:'Night Blue',icon:'☾',class:'mood-night',desc:'Quiet blue for slower hours'},
  mist:{name:'Morning Mist',icon:'☁',class:'mood-mist',desc:'Cool, airy and fresh'}
};
const app=document.getElementById('app');
function currentMood(){return localStorage.getItem('bloomMood')||'soft'}
function applyMood(key=currentMood()){
  if(!moods[key]) key='soft';
  document.body.dataset.mood=key;
  document.documentElement.style.setProperty('--mood',`"${key}"`);
  localStorage.setItem('bloomMood',key);
}
function shell(content,key){return `<div class="ambient-layer"><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><div class="stars"></div></div><main class="site"><nav class="nav"><div class="nav-left"><a class="back" href="#" id="backBtn" aria-label="Go back">← <span>Back</span></a><a class="logo" href="#/home">bloom<span>°</span></a></div><div class="navlinks"><a href="#/breathe">Breathe</a><a href="#/journal">Journal</a><a href="#/future">Future</a><a href="#/comfort">Comfort</a><a href="#/poetry">Poetry</a></div><div class="nav-tools"><button class="mood-button" id="moodBtn" aria-label="Choose mood">☼ <span>Soft Light</span></button><button class="sound" id="soundBtn">♪ Ambient</button></div></nav><div class="mood-panel" id="moodPanel"><div class="mood-panel-head"><div><b>Choose your atmosphere</b><small>The choice is remembered on this device.</small></div><button id="closeMood" aria-label="Close">×</button></div><div class="mood-options">${Object.entries(moods).map(([id,m])=>`<button class="mood-option" data-mood="${id}"><span class="mood-icon">${m.icon}</span><span><b>${m.name}</b><small>${m.desc}</small></span><i>✓</i></button>`).join('')}</div></div>${content}<footer class="footer"><span>Made for the days that feel too quiet.</span><div><a href="#/poetry">A few words</a><a href="#/about">About Bloom</a></div></footer></main>`}
async function route(){let key=location.hash.replace('#/','')||'home';if(!pages[key])key='home';let html=await fetch(pages[key]).then(r=>r.text());app.innerHTML=shell(html,key);applyMood();document.querySelectorAll('.navlinks a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#/${key}`));updateMoodUI();bind(key)}
function updateMoodUI(){const key=currentMood(),m=moods[key];const b=document.getElementById('moodBtn');if(b)b.innerHTML=`${m.icon} <span>${m.name}</span>`;document.querySelectorAll('.mood-option').forEach(x=>x.classList.toggle('selected',x.dataset.mood===key))}
function bind(key){
 const back=document.getElementById('backBtn');back.onclick=(e)=>{e.preventDefault();if(history.length>1){history.back();setTimeout(()=>{if(!location.hash||location.hash==='#')location.hash='#/home'},150)}else location.hash='#/home'};
 const panel=document.getElementById('moodPanel');document.getElementById('moodBtn').onclick=()=>panel.classList.toggle('open');document.getElementById('closeMood').onclick=()=>panel.classList.remove('open');document.querySelectorAll('.mood-option').forEach(b=>b.onclick=()=>{applyMood(b.dataset.mood);updateMoodUI();panel.classList.remove('open');spark()});
 document.addEventListener('click',e=>{if(panel.classList.contains('open')&&!panel.contains(e.target)&&!e.target.closest('#moodBtn'))panel.classList.remove('open')},{once:true});
 document.getElementById('soundBtn').onclick=()=>{let b=document.getElementById('soundBtn');let a=window.__audio;if(a){a.osc.stop();a.ctx.close();window.__audio=null;b.textContent='♪ Ambient'}else{let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;let ac=new AC(),o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.value=currentMood()==='night'?174:196;g.gain.value=.014;o.connect(g).connect(ac.destination);o.start();window.__audio={ctx:ac,osc:o};b.textContent='◼ Ambient'}};
 if(key==='breathe'){let orb=document.getElementById('breathOrb'),txt=document.getElementById('breathText'),timer=document.getElementById('breathTimer'),btn=document.getElementById('startBreath');btn.onclick=()=>{let t=60;btn.disabled=true;orb.classList.add('running');txt.textContent='In…';let iv=setInterval(()=>{t--;timer.textContent=t;txt.textContent=(t%8<4)?'In…':'Out…';if(t<=0){clearInterval(iv);orb.classList.remove('running');txt.textContent='You made it';btn.disabled=false}},1000)}}
 if(key==='journal'){const prompts=['What do you wish someone had told you on your hardest day?','What part of yourself deserves more kindness lately?','What is something you survived that you once thought you could not?','What would a peaceful evening look like for you?','What is one memory you can keep without letting it define you?','What would you say to yourself if you spoke with complete tenderness?'];let i=0;let p=document.getElementById('promptText');document.getElementById('newPrompt').onclick=()=>{i=(i+1)%prompts.length;p.textContent=prompts[i];spark()};let ta=document.getElementById('journalText'),state=document.getElementById('saveState');ta.value=localStorage.getItem('bloomJournal')||'';document.getElementById('saveJournal').onclick=()=>{localStorage.setItem('bloomJournal',ta.value);state.textContent='Saved just here · '+new Date().toLocaleTimeString()};document.getElementById('clearJournal').onclick=()=>{ta.value='';localStorage.removeItem('bloomJournal');state.textContent='Cleared'}}
 if(key==='future'){const prompts=['What is one thing you would love to experience for the first time?','Where would you go if you could wake up anywhere tomorrow?','What hobby would you try if nobody judged you?','What would make your next month feel 1% brighter?','What kind of person do you want to become for yourself?','What small plan would make you smile when you wake up?'];let i=0;let p=document.getElementById('futurePrompt');document.getElementById('shuffleFuture').onclick=()=>{i=(i+1)%prompts.length;p.textContent=prompts[i];spark()};const chips=['learn something','watch sunrise','make art','visit somewhere new','cook','read','walk','dance','take photos','plant something'];document.getElementById('futureChips').innerHTML=chips.map(x=>`<button class="chip" onclick="this.classList.toggle('picked')">${x}</button>`).join('')}
 if(key==='comfort'){const lines=['You are allowed to miss someone and still choose yourself.','A bad night is not a forecast for your whole life.','You do not need to be over it today. Just be gentle with today.','The future does not need permission from the past.','Rest is still progress when your heart is tired.','There are people you have not met yet who will know the softer version of you.','You deserve comfort that does not ask you to become someone else.'];let i=0;document.getElementById('comfortNext').onclick=()=>{i=(i+1)%lines.length;document.getElementById('comfortLine').animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:450});document.getElementById('comfortLine').textContent=lines[i]}}
 if(key==='poetry'){const poems=[['After the Rain','Some mornings arrive quietly,\nnot asking you to be happy,\nonly asking you to open the curtain\nand notice the light has returned.\n\nYou can carry yesterday gently\nwithout carrying it everywhere.\nLet the day be small.\nLet your heart take its time.'],['A Place for Tomorrow','There is a version of tomorrow\nthat has never heard the old story.\nShe is still learning your favorite songs,\nstill waiting for your laughter,\nstill becoming home.\n\nYou do not have to chase her.\nJust keep walking softly.'],['Little Things','A cup of tea.\nA window left open.\nA song you forgot you loved.\nThe sky turning gold on an ordinary road.\n\nSometimes healing enters\nwithout announcing its name.'],['When It Gets Quiet','If the room becomes too quiet,\nput one gentle thing inside it:\na page, a melody, a plant, a warm light.\n\nYou are not required\nto solve your whole life tonight.\nOnly make tonight kinder.']];let i=0;const title=document.getElementById('poemTitle'),text=document.getElementById('poemText');document.getElementById('nextPoem').onclick=()=>{i=(i+1)%poems.length;title.textContent=poems[i][0];text.textContent=poems[i][1];spark()};document.getElementById('copyPoem').onclick=async()=>{try{await navigator.clipboard.writeText(title.textContent+'\n\n'+text.textContent);document.getElementById('copyPoem').textContent='Copied ✓';setTimeout(()=>document.getElementById('copyPoem').textContent='Copy poem',1300)}catch(e){}}}
}
function spark(){for(let i=0;i<10;i++){let s=document.createElement('i');s.textContent=Math.random()>.5?'✦':'·';s.style.position='fixed';s.style.left=(45+Math.random()*10)+'%';s.style.top=(45+Math.random()*10)+'%';s.style.color='var(--accent)';s.style.pointerEvents='none';s.style.zIndex=20;document.body.appendChild(s);s.animate([{transform:'scale(0)',opacity:0},{transform:`translate(${(Math.random()-.5)*220}px,${(Math.random()-.5)*170}px) scale(1)`,opacity:1},{opacity:0}],{duration:1100}).onfinish=()=>s.remove()}}
window.addEventListener('hashchange',route);route();
