(function(){'use strict';
const A=document.getElementById('app');
const moods={soft:{name:'Soft Light',icon:'☼',desc:'Warm, golden and gentle'},night:{name:'Night Blue',icon:'☾',desc:'Quiet, deep and dreamy'},mist:{name:'Morning Mist',icon:'☁',desc:'Fresh, airy and hopeful'}};
const daily=[['A tiny beginning','You do not need to feel completely okay today. One gentle thing is enough.','Take a breath'],['A softer thought','Some chapters end without taking your whole story with them. There is still so much unwritten.','Write three lines'],['For tonight','If your mind returns to yesterday, give it somewhere kinder to go: music, a page, the sky.','Look at the sky'],['A little courage','Healing can be wonderfully ordinary. Tea. A walk. Clean sheets. A laugh you did not expect.','Do one small thing'],['You are still becoming','The person you are becoming deserves the same patience you give everyone else.','Be kind to yourself'],['No rush','There is no deadline for feeling better. Let today be today. Tomorrow can wait.','Take five slow breaths'],['Something ahead','There are mornings you have not lived yet that will feel lighter than you imagine.','Imagine one']];
const poems=[['After the Rain','Some mornings arrive quietly,\nnot asking you to be brave.\nJust opening the curtains\nand leaving a little gold\non the floor.\n\nYou do not have to run\ntoward a new life.\nSometimes healing begins\nwith noticing\nthat the light came back.'],['A Place for Tomorrow','Keep a small room\ninside your heart\nthat yesterday cannot enter.\n\nPut a chair there.\nPut a window there.\nPut your favourite song\nplaying softly.\n\nTomorrow may knock\nwhen you are not ready.\nLet it.'],['Little Things','A clean shirt.\nWarm food.\nA silly video.\nRain against the glass.\nA friend saying your name.\n\nLife rarely announces\nwhen it is getting better.\nIt simply leaves\nsmall gifts\nat the edge of an ordinary day.'],['When It Gets Quiet','When the room gets quiet\nand your thoughts become loud,\nremember:\nyou are allowed\nto choose a gentler thought.\n\nNot every memory\nneeds an answer.\nNot every feeling\nneeds a decision.\n\nTonight can simply be tonight.']];
const prompts=['What would feel kind to you right now?','What is one tiny thing you are proud of today?','What do you wish someone could say to you?','What would you like your future self to remember?','What made you smile, even for a second?','What can wait until tomorrow?'];
const comfort=['You are allowed to miss someone and still choose yourself.','You do not have to heal on anyone else’s schedule.','A hard evening is not a hard life.','You can be tender with yourself without staying stuck.','There are people and places you have not met yet.','Rest is not falling behind.','Your story is bigger than one chapter.','You deserve ordinary days that feel peaceful.'];
const future=['What would you love to experience for the first time?','What place would you like to see one day?','What skill would be fun to learn just because you can?','What kind of morning would make you happy to wake up?','What small adventure could you plan this month?'];
function get(k,d){try{return localStorage.getItem(k)??d}catch(e){return d}}function set(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function idx(n){const d=new Date();return (d.getFullYear()*372+d.getMonth()*31+d.getDate())%n}
function mood(){let k=get('bloomMood','soft');return moods[k]?k:'soft'}
function applyMood(k){if(!moods[k])k='soft';document.body.dataset.mood=k;set('bloomMood',k);document.querySelector('meta[name=theme-color]').setAttribute('content',k==='night'?'#081525':k==='mist'?'#dfecef':'#f4eee7')}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(content,key){const nav=[['home','⌂','Home'],['breathe','◌','Breathe'],['journal','✎','Write'],['future','✦','Future'],['comfort','♡','Comfort'],['poetry','❋','Poetry'],['garden','✺','Garden']];return `<div class="ambient-layer"><div class="aurora a1"></div><div class="aurora a2"></div><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><div class="stars"></div><div class="grain"></div><div class="cursor-glow"></div></div><main class="site"><nav class="nav"><div class="nav-left"><button class="back" id="backBtn" aria-label="Go back">← <span>Back</span></button><a class="logo" href="#/home">bloom<span>°</span></a></div><div class="navlinks">${nav.map(x=>`<a href="#/${x[0]}" class="${key===x[0]?'active':''}">${x[1]} ${x[2]}</a>`).join('')}</div><div class="nav-tools"><button class="mood-button" id="moodBtn">${moods[mood()].icon} <span>${moods[mood()].name}</span></button><button class="sound" id="soundBtn" title="Ambient music">♪</button><button class="menu" id="menuBtn">☰</button></div></nav><div class="mobile-menu" id="mobileMenu">${nav.map(x=>`<a href="#/${x[0]}">${x[1]} ${x[2]}</a>`).join('')}</div><div class="presence-line"><span class="presence-dot"></span><span id="presenceText"></span><span class="presence-sep">·</span><span id="musicState">ambient ready</span></div><div class="mood-panel" id="moodPanel"><div class="mood-panel-head"><div><b>Choose your atmosphere</b><small>Your choice stays on this device.</small></div><button id="closeMood">×</button></div><div class="mood-options">${Object.entries(moods).map(([id,m])=>`<button class="mood-option" data-mood="${id}"><span class="mood-icon">${m.icon}</span><span><b>${m.name}</b><small>${m.desc}</small></span><i>✓</i></button>`).join('')}</div></div>${content}<footer class="footer"><span>For the days that feel too quiet.</span><div><a href="#/about">About Bloom</a><a href="#/poetry">A few words</a></div></footer><div class="bottom-nav">${nav.slice(0,5).map(x=>`<a href="#/${x[0]}" class="${key===x[0]?'active':''}"><span>${x[1]}</span>${x[2]}</a>`).join('')}</div></main><div class="toast" id="toast"></div>`}
function home(){
const d=daily[idx(daily.length)];let visits=Number(get('visits','0'))+1;set('visits',visits);
const cards=[['breathe','◌','Breathe',"A tiny guided pause for when your thoughts won't sit still.",'60 seconds · gentle'],['journal','✎','Write','Put the messy version on a page. No audience. No perfect sentences.','private · on this device'],['future','✦','Future','Small ideas for tomorrow, next month, and the life still waiting to surprise you.','shuffle · explore'],['comfort','♡','Comfort','Short reminders for moments when your own mind is being harder on you than it should.','tap for another'],['poetry','❋','Poetry','Original little pieces to read when advice feels like too much.','new words · daily'],['about','☼','Your space','Change the atmosphere, sound and tiny details until this corner feels like yours.','soft · night · mist']];
const cardHtml=cards.map(function(x,i){return '<a href="#/'+x[0]+'" class="feature micro-card"><b>0'+(i+1)+' · '+x[2].toUpperCase()+'</b><div class="feature-icon">'+x[1]+'</div><h3>'+x[2]+'</h3><p>'+x[3]+'</p><span>'+x[4]+'</span></a>'}).join('');
return `<section class="hero page-enter"><div class="eyebrow">a quiet corner of the internet · <span>${Math.min(visits,999)} gentle visit${visits===1?'':'s'}</span></div><h1>You don't have to forget.<br><span>You can begin again.</span></h1><p class="lead">A little place to breathe when thoughts get loud. Come for one minute, ten minutes, or simply because you want somewhere soft to land.</p><div class="actions"><a class="btn primary" href="#/breathe">Take a breath <span>→</span></a><a class="btn ghost" href="#/poetry">Read something gentle</a></div><div class="daily-card glass"><div class="daily-icon">✦</div><div><span class="label">a little note for today</span><h3>${esc(d[0])}</h3><p>${esc(d[1])}</p><button class="text-btn" id="dailyAction">${esc(d[2])} →</button></div></div></section><section class="rituals glass"><div class="ritual-head"><div><span class="eyebrow">a tiny ritual for now</span><h2>You only need to choose one.</h2></div><span class="ritual-count" id="ritualCount">0 chosen today</span></div><div class="ritual-grid"><button class="ritual" data-ritual="drink some water"><span>01</span><b>Drink some water</b><small>Just a few slow sips.</small></button><button class="ritual" data-ritual="open a window"><span>02</span><b>Open a window</b><small>Let the room change a little.</small></button><button class="ritual" data-ritual="listen to one song"><span>03</span><b>Listen to one song</b><small>No scrolling. Just listen.</small></button><button class="ritual" data-ritual="stretch for one minute"><span>04</span><b>Stretch for one minute</b><small>Let your shoulders soften.</small></button></div><p class="ritual-note" id="ritualNote">There is no prize for doing all four. One is enough.</p></section><section class="section-head"><div><span class="eyebrow">choose what you need</span><h2>There is no right way to use Bloom.</h2></div><p>Wander around. Stay for a moment. Leave and return tomorrow. Nothing here is a test.</p></section><section class="feature-grid">${cardHtml}</section><section class="night-note glass"><div id="constellation" class="constellation"></div><span class="eyebrow">a thought to keep</span><p>“You are not behind. You are becoming, even on the days when it doesn't look like anything is happening.”</p><span class="tiny">The atmosphere changes gently with the time of day.</span></section>`}

function page(key){if(key==='home')return home();if(key==='breathe')return `<section class="center-page page-enter"><span class="eyebrow">01 · slow down</span><h1>Let's make <span>one minute</span> quieter.</h1><p class="lead">Follow the circle. Let your shoulders drop a little.</p><div class="breath-wrap"><div class="breath-orb" id="breathOrb"><span id="breathText">Ready</span></div></div><div class="timer" id="breathTimer">60</div><button class="btn primary" id="startBreath">Start 60 seconds</button><p class="tiny">Your breathing does not have to be perfect.</p></section><section class="three-notes"><div><b>In</b><p>Let the breath arrive without forcing it.</p></div><div><b>Notice</b><p>Feel your feet, hands and the room around you.</p></div><div><b>Out</b><p>Make a little more room inside yourself.</p></div></section>`;
if(key==='journal')return `<section class="page-head page-enter"><span class="eyebrow">02 · let it out</span><h1>A page that <span>doesn't interrupt.</span></h1><p class="lead">Write badly. Write honestly. Write three words and leave.</p></section><section class="journal-grid"><div class="prompt glass"><span>today's gentle prompt</span><h2 id="promptText"></h2><button class="text-btn" id="newPrompt">Another prompt ↻</button><div class="prompt-foot">No one is grading this.</div></div><div class="editor glass"><textarea id="journalText" placeholder="Start anywhere…&#10;&#10;You could begin with: “Today I…”"></textarea><div class="editor-foot"><span id="wordCount">0 words</span><span id="saveState">Not saved yet</span><div><button class="btn ghost small" id="clearJournal">Clear</button><button class="btn primary small" id="saveJournal">Save</button></div></div></div></section>`;
if(key==='future')return `<section class="center-page page-enter"><span class="eyebrow">03 · look forward</span><h1>There is still <span>so much life.</span></h1><p class="lead">Not a giant plan. Just little doors you might like to open.</p><div class="future-card glass"><div class="sun">☼</div><h2 id="futurePrompt"></h2><button class="btn ghost" id="shuffleFuture">Give me another idea ↻</button><div class="chips" id="futureChips"></div></div></section><section class="mini-grid"><div><b>For a free afternoon</b><p>Walk somewhere new. Take photos. Try a snack you have never had.</p></div><div><b>For a difficult evening</b><p>Shower. Change the sheets. Put on something familiar. Make tea.</p></div><div><b>For a future morning</b><p>Wake early once. Watch the sky change. You don't need a reason beyond being there.</p></div></section>`;
if(key==='comfort')return `<section class="center-page page-enter"><span class="eyebrow">04 · borrow warmth</span><h1>For when your mind is <span>too loud.</span></h1><p class="lead">Take one sentence. Keep it for as long as you need.</p><div class="comfort-card glass"><p id="comfortLine"></p><button class="btn primary" id="comfortNext">Another little reminder</button></div><p class="tiny smalllead">You don't have to turn pain into a lesson tonight.</p></section><section class="principles glass"><div><b>Soft does not mean weak.</b><p>Rest, quiet and asking for company can all be forms of taking care.</p></div><div><b>You can have mixed feelings.</b><p>Missing something doesn't mean you need the whole thing back.</p></div><div><b>Tomorrow can be different.</b><p>A feeling can be real without being permanent.</p></div></section>`;
if(key==='poetry')return `<section class="page-head page-enter"><span class="eyebrow">05 · read slowly</span><h1>A few words for the <span>quiet hours.</span></h1><p class="lead">Original little poems for moments when advice feels like too much.</p></section><article class="poem-card glass"><span class="poem-mark">❋</span><h2 id="poemTitle"></h2><div class="poem-text" id="poemText"></div><div class="poem-actions"><button class="btn primary" id="nextPoem">Another poem →</button><button class="btn ghost" id="copyPoem">Copy</button></div></article><div class="poetry-note glass"><b>You can read the same poem twice.</b><p>Some words change when you return to them.</p></div>`;
if(key==='garden')return `<section class="page-head page-enter"><span class="eyebrow">06 · a tiny piece of code</span><h1>A garden that <span>grows with you.</span></h1><p class="lead">A small generative experiment: every dot, stem and glow is drawn by code in your browser. Nothing is uploaded. Change the feeling, and the garden quietly changes with it.</p></section><section class="garden-panel glass"><div class="garden-top"><div><span class="eyebrow">generative garden</span><h2 id="gardenTitle">A little life, rendered in real time.</h2></div><button class="btn ghost" id="growGarden">Grow something new ↗</button></div><div class="garden-canvas-wrap"><canvas id="gardenCanvas" aria-label="Animated generative garden"></canvas><div class="garden-overlay"><span id="gardenSeed">seed · 0000</span><span>local · private · procedural</span></div></div><div class="garden-controls"><button class="garden-feel active" data-feel="calm">calm</button><button class="garden-feel" data-feel="hopeful">hopeful</button><button class="garden-feel" data-feel="dreamy">dreamy</button><button class="garden-feel" data-feel="wild">wild</button></div><p class="garden-caption" id="gardenCaption">Some things grow slowly enough that you only notice them when you look back.</p></section><section class="code-note glass"><div class="code-orb">{ }</div><div><span class="eyebrow">the CSE detail</span><h3>No two gardens are exactly the same.</h3><p>The garden uses a tiny deterministic pseudo-random generator, layered noise, particle physics and your chosen feeling to create its scene. Your journal text is never sent into the generator.</p></div></section>`;
return `<section class="center-page page-enter"><span class="eyebrow">07 · about bloom</span><h1>A small place to <span>land.</span></h1><p class="lead">An intentionally simple corner of the internet that asks nothing from you.</p><div class="principles glass"><div><b>Make the atmosphere yours.</b><p>Soft Light, Night Blue and Morning Mist are remembered on this device.</p></div><div><b>Private by default.</b><p>The journal stays in this browser in this version.</p></div><div><b>Little surprises.</b><p>Bloom changes its daily note, stars, particles and atmosphere so it doesn't feel exactly the same each visit.</p></div><div><b>For real support too.</b><p>A website can be comforting, but trusted people and professionals matter when life feels too heavy.</p></div></div></section>`}
function toast(s){const t=document.getElementById('toast');if(!t)return;t.textContent=s;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
let audio=null;
const musicByMood={soft:'assets/soft-light.wav',night:'assets/night-blue.wav',mist:'assets/morning-mist.wav'};
let musicWanted=get('bloomMusicOn','1')!=='0';
let userHasInteracted=get('bloomMusicGesture','0')==='1';
let currentTrack='';
function musicPath(){return musicByMood[mood()]||musicByMood.soft}
function currentMusicUrl(src){try{return new URL(src,location.href).href}catch(e){return src}}
function ensureAudio(){
  if(audio)return audio;
  audio=new Audio();
  audio.loop=true;
  audio.volume=.09;
  audio.preload='auto';
  audio.setAttribute('playsinline','');
  audio.setAttribute('aria-label','Bloom ambient music');
  audio.addEventListener('error',()=>updateSoundButton());
  return audio;
}
function startAmbient(showToastOnFail=false){
  if(!musicWanted)return Promise.resolve(false);
  const a=ensureAudio(),src=musicPath();
  if(a.src!==currentMusicUrl(src)){
    a.src=src;
    a.load();
    currentTrack=src;
  }
  a.volume=.09;
  const p=a.play();
  if(p&&p.then){
    return p.then(()=>{updateSoundButton();return true}).catch(()=>{
      updateSoundButton();
      if(showToastOnFail)toast('Tap anywhere once and Bloom will play softly ♡');
      return false;
    });
  }
  updateSoundButton();
  return Promise.resolve(!a.paused);
}
function updateSoundButton(){
  const b=document.getElementById('soundBtn');
  if(b){b.textContent=(audio&&!audio.paused)?'◼':'♪';b.setAttribute('aria-label',(audio&&!audio.paused)?'Pause ambient music':'Play ambient music')}
}
function audioToggle(){
  const a=ensureAudio();
  if(!a.paused){a.pause();musicWanted=false;set('bloomMusicOn','0');updateSoundButton();toast('Ambient paused · tap ♪ whenever you want it back');return}
  musicWanted=true;set('bloomMusicOn','1');userHasInteracted=true;set('bloomMusicGesture','1');startAmbient(true).then(ok=>{if(ok)toast('Ambient music on · very softly')});
}
function changeAmbientForMood(){
  if(!musicWanted)return;
  const a=ensureAudio(),src=musicPath();
  if(a.src===currentMusicUrl(src)){if(a.paused&&userHasInteracted)startAmbient(false);return}
  const wasPlaying=!a.paused;
  const old=.09;
  if(wasPlaying){
    a.volume=.03;
    setTimeout(()=>{
      a.pause();a.src=src;a.load();currentTrack=src;a.volume=0;
      const p=a.play();
      if(p&&p.catch)p.catch(()=>{});
      let v=0;const up=setInterval(()=>{v+=.01;a.volume=Math.min(old,v);if(v>=old)clearInterval(up)},60);
    },140);
  }else{a.src=src;a.load();currentTrack=src;a.volume=old;if(userHasInteracted)startAmbient(false);}
}
function handleFirstGesture(){
  if(userHasInteracted)return;
  userHasInteracted=true;
  set('bloomMusicGesture','1');
  if(musicWanted)startAmbient(false);
}
function enableAutoplayFallback(){
  if(!musicWanted)return;
  startAmbient(false).then(ok=>{
    if(ok)return;
    // Browsers may block audible autoplay. The first real interaction anywhere on the page unlocks it.
  });
}

function updatePresence(){
  const h=new Date().getHours();
  let greeting='A quiet place for right now.';
  if(h<5)greeting='The world is quiet. You can be gentle with yourself.';
  else if(h<10)greeting='A new morning does not need a perfect beginning.';
  else if(h<14)greeting='There is still plenty of day left for small good things.';
  else if(h<19)greeting='Take the afternoon one soft moment at a time.';
  else greeting='Let tonight be a place to put things down.';
  const p=document.getElementById('presenceText');if(p)p.textContent=greeting;
  const m=document.getElementById('musicState');if(m)m.textContent=(audio&&!audio.paused)?'playing softly':'tap anywhere · music will begin';
}

function bind(key){const back=document.getElementById('backBtn');back.onclick=e=>{e.preventDefault();if(history.length>1)history.back();else location.hash='#/home'};const panel=document.getElementById('moodPanel');document.getElementById('moodBtn').onclick=()=>panel.classList.toggle('open');document.getElementById('closeMood').onclick=()=>panel.classList.remove('open');document.querySelectorAll('.mood-option').forEach(b=>b.onclick=()=>{applyMood(b.dataset.mood);updateMood();changeAmbientForMood();panel.classList.remove('open');spark()});document.getElementById('menuBtn').onclick=()=>document.getElementById('mobileMenu').classList.toggle('open');document.querySelectorAll('.mobile-menu a').forEach(a=>a.onclick=()=>document.getElementById('mobileMenu').classList.remove('open'));document.getElementById('soundBtn').onclick=audioToggle; updatePresence(); if(key==='home')bindHome();if(key==='breathe')bindBreathe();if(key==='journal')bindJournal();if(key==='future')bindFuture();if(key==='comfort')bindComfort();if(key==='poetry')bindPoetry()}
function updateMood(){const k=mood(),b=document.getElementById('moodBtn');if(b)b.innerHTML=moods[k].icon+' <span>'+moods[k].name+'</span>';document.querySelectorAll('.mood-option').forEach(x=>x.classList.toggle('selected',x.dataset.mood===k))}
function bindHome(){const c=document.getElementById('constellation');if(c)for(let i=0;i<25;i++){const s=document.createElement('i');s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*3+'s';c.appendChild(s)}document.getElementById('dailyAction').onclick=()=>{const n=daily[idx(daily.length)][2];toast(n+' ✦')};document.querySelectorAll('.micro-card').forEach(c=>c.addEventListener('click',()=>{c.classList.add('done');setTimeout(()=>c.classList.remove('done'),700)}));const rituals=[...document.querySelectorAll('.ritual')],count=document.getElementById('ritualCount'),note=document.getElementById('ritualNote');let chosen=[];try{const saved=JSON.parse(get('bloomRituals','[]'));chosen=Array.isArray(saved)?saved:[]}catch(e){}const render=()=>{rituals.forEach(r=>r.classList.toggle('picked',chosen.includes(r.dataset.ritual)));if(count)count.textContent=chosen.length+' chosen today';if(note&&chosen.length)note.textContent=chosen.length===1?'One small kindness is enough for today.':chosen.length===2?'Two is lovely. You can stop here.':chosen.length===3?'Three is plenty. Leave the rest for another day.':'You did four. Now go be wonderfully ordinary for a while.'};rituals.forEach(r=>r.onclick=()=>{const v=r.dataset.ritual;chosen=chosen.includes(v)?chosen.filter(x=>x!==v):[...chosen,v];set('bloomRituals',JSON.stringify(chosen));render();spark()});render()}
function bindBreathe(){const o=document.getElementById('breathOrb'),t=document.getElementById('breathText'),tm=document.getElementById('breathTimer'),b=document.getElementById('startBreath');b.onclick=()=>{let n=60;b.disabled=true;o.classList.add('running');let iv=setInterval(()=>{n--;tm.textContent=n;t.textContent=n%8<4?'In…':'Out…';if(n<=0){clearInterval(iv);o.classList.remove('running');t.textContent='You made it';b.disabled=false;spark();toast('A minute just became softer.')}},1000)}}
function bindJournal(){let i=Number(get('promptIndex','0'))%prompts.length,p=document.getElementById('promptText');p.textContent=prompts[i];const ta=document.getElementById('journalText'),state=document.getElementById('saveState'),count=document.getElementById('wordCount');ta.value=get('journal','');const countIt=()=>count.textContent=(ta.value.trim()?ta.value.trim().split(/\s+/).length:0)+' words';countIt();ta.oninput=countIt;document.getElementById('newPrompt').onclick=()=>{i=(i+1)%prompts.length;set('promptIndex',i);p.textContent=prompts[i];spark()};document.getElementById('saveJournal').onclick=()=>{set('journal',ta.value);state.textContent='Saved privately · '+new Date().toLocaleTimeString();toast('Your words are safe here ✦')};document.getElementById('clearJournal').onclick=()=>{ta.value='';set('journal','');countIt();state.textContent='Cleared'}}
function bindFuture(){let i=idx(future.length),p=document.getElementById('futurePrompt');p.textContent=future[i];document.getElementById('shuffleFuture').onclick=()=>{i=(i+1)%future.length;p.textContent=future[i];spark()};const chips=['learn something','watch a sunrise','make art','visit somewhere new','cook something','read a book','take a long walk','dance','take photos','plant something','try a new café','make a playlist'];document.getElementById('futureChips').innerHTML=chips.map(x=>`<button class="chip">${x}</button>`).join('');document.querySelectorAll('.chip').forEach(x=>x.onclick=()=>{x.classList.toggle('picked');x.textContent=x.classList.contains('picked')?'✓ '+x.textContent:x.textContent.replace(/^✓ /,'')})}
function bindComfort(){let i=idx(comfort.length),line=document.getElementById('comfortLine');line.textContent=comfort[i];document.getElementById('comfortNext').onclick=()=>{i=(i+1)%comfort.length;line.textContent=comfort[i];spark()}}
function bindPoetry(){let i=idx(poems.length),title=document.getElementById('poemTitle'),text=document.getElementById('poemText');const render=()=>{title.textContent=poems[i][0];text.textContent=poems[i][1]};render();document.getElementById('nextPoem').onclick=()=>{i=(i+1)%poems.length;render();spark()};document.getElementById('copyPoem').onclick=()=>{const v=title.textContent+'\n\n'+text.textContent;if(navigator.clipboard)navigator.clipboard.writeText(v).then(()=>toast('Poem copied')).catch(()=>toast('Copy unavailable'));else toast('Copy unavailable')}}
function bindGarden(){const c=document.getElementById('gardenCanvas'),wrap=c&&c.parentElement;if(!c)return;const ctx=c.getContext('2d');let feel='calm',seed=Number(get('gardenSeed','0'))||Math.floor(Math.random()*999999),raf=0,alive=true;const title=document.getElementById('gardenTitle'),caption=document.getElementById('gardenCaption'),seedEl=document.getElementById('gardenSeed');const captions={calm:'Some things grow slowly enough that you only notice them when you look back.',hopeful:'There are tiny green things in every future you have not reached yet.',dreamy:'Not everything beautiful needs to be explained before it can be enjoyed.',wild:'A little unpredictability is another word for possibility.'};const resize=()=>{const d=Math.min(devicePixelRatio||1,2),r=wrap.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;c.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0)};function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function draw(t){if(!alive)return;const w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);const base={calm:0.16,hopeful:0.32,dreamy:0.23,wild:0.55}[feel];for(let i=0;i<75;i++){const x=(i*97+seed*0.013)%w,y=(i*53+seed*0.021+Math.sin(t/2500+i)*18)%h,r=1+rng()*3;ctx.globalAlpha=.12+.3*rng();ctx.beginPath();ctx.arc(x,y,r+Math.sin(t/700+i)*.6,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.9)';ctx.fill()}const n=feel==='wild'?34:24;for(let i=0;i<n;i++){const x=(rng()*0.92+.04)*w;const ground=h-(18+rng()*28);const height=(.16+rng()*.62)*h*(.65+base);ctx.strokeStyle='rgba(111,145,120,.58)';ctx.lineWidth=1+rng()*1.4;ctx.beginPath();ctx.moveTo(x,ground);ctx.quadraticCurveTo(x+(rng()-.5)*45,ground-height*.55,x+(rng()-.5)*70,ground-height);ctx.stroke();const petals=3+(rng()*4|0);for(let j=0;j<petals;j++){const px=x+(rng()-.5)*75,py=ground-height+rng()*25;ctx.globalAlpha=.45+.35*rng();ctx.fillStyle=feel==='dreamy'?'rgba(214,191,225,.72)':feel==='hopeful'?'rgba(216,196,119,.72)':'rgba(201,218,202,.72)';ctx.beginPath();ctx.arc(px,py,2+rng()*3,0,Math.PI*2);ctx.fill()}}ctx.globalAlpha=1;raf=requestAnimationFrame(draw)}function rebuild(){seed=Math.floor(Math.random()*999999);set('gardenSeed',String(seed));seedEl.textContent='seed · '+String(seed).padStart(6,'0');caption.textContent=captions[feel];title.textContent=feel==='wild'?'A garden with a little chaos.':feel==='dreamy'?'A garden made of soft possibilities.':feel==='hopeful'?'A garden pointed toward tomorrow.':'A garden that grows quietly.';spark()}document.querySelectorAll('.garden-feel').forEach(b=>b.onclick=()=>{document.querySelectorAll('.garden-feel').forEach(x=>x.classList.remove('active'));b.classList.add('active');feel=b.dataset.feel;rebuild()});document.getElementById('growGarden').onclick=rebuild;window.addEventListener('resize',resize);resize();rebuild();raf=requestAnimationFrame(draw);setTimeout(()=>{alive=false;cancelAnimationFrame(raf)},1000*60*10)}
function spark(){for(let i=0;i<10;i++){const s=document.createElement('i');s.textContent=Math.random()>.4?'✦':'·';s.style.position='fixed';s.style.left=(45+Math.random()*10)+'%';s.style.top=(45+Math.random()*10)+'%';s.style.color='var(--accent)';s.style.zIndex=100;s.style.pointerEvents='none';document.body.appendChild(s);const dx=(Math.random()-.5)*260,dy=(Math.random()-.5)*190;const a=s.animate([{transform:'scale(0)',opacity:0},{transform:`translate(${dx}px,${dy}px) scale(1)`,opacity:1},{opacity:0}],{duration:1000});a.onfinish=()=>s.remove()}}
function route(){let key=(location.hash||'#/home').replace('#/','');if(!['home','breathe','journal','future','comfort','poetry','garden','about'].includes(key))key='home';A.innerHTML=shell(page(key),key);applyMood(mood());updateMood();bind(key);enableAutoplayFallback();requestAnimationFrame(()=>document.querySelectorAll('.page-enter').forEach(x=>x.classList.add('show')))}
window.addEventListener('hashchange',route);document.addEventListener('pointerdown',handleFirstGesture,{passive:true});document.addEventListener('touchstart',handleFirstGesture,{passive:true});document.addEventListener('keydown',handleFirstGesture,{passive:true});document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')},{passive:true});
try{const h=new Date().getHours();if(h>=20||h<6)set('autoMood','night');else if(h<10)set('autoMood','mist')}catch(e){} route();
})();
